# Worker service config. Railway service Config File path: /railway.worker.toml
[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
watchPatterns = ["backend/**", "public/sources.yaml", "railway.worker.toml"]

[deploy]
startCommand = "celery -A celery_app.celery worker --loglevel=INFO --concurrency=4"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
overlapSeconds = "20"
drainingSeconds = "60"
