SEED_ARTICLES = [
    ("中国电建签署沙特光伏项目 EPC 合同","中国电建","official","沙特阿拉伯","中东","光伏新能源","https://www.powerchina.cn/"),
    ("NEOM 发布数据中心园区采购预告","NEOM","procurement","沙特阿拉伯","中东","数据中心","https://www.neom.com/"),
    ("中国能建葛洲坝中标越南输变电工程","EVN","official","越南","东南亚","电网","https://en.evn.com.vn/"),
    ("墨西哥克雷塔罗数据中心投资计划","Mexico Business News","media","墨西哥","拉美","数据中心","https://mexicobusiness.news/"),
    ("ADB 批准菲律宾岛屿微电网项目","ADB","procurement","菲律宾","东南亚","微电网","https://www.adb.org/projects/tenders"),
    ("ABB 在阿联酋发布数字化配电方案","ABB","competitor","阿联酋","中东","基础设施","https://global.abb/group/en/media/news"),
    ("中交集团印尼港口项目进入机电安装","中交集团","official","印度尼西亚","东南亚","港口","https://www.ccccltd.cn/"),
    ("世界银行发布埃及配电网采购预告","World Bank","procurement","埃及","非洲","电网","https://projects.worldbank.org/en/projects-operations/procurement"),
    ("中国铁建签约马来西亚轨交项目","中国铁建","official","马来西亚","东南亚","轨道交通","https://www.crcc.cn/"),
    ("沙特电力启动变电站供应商注册","Saudi Electricity Company","official","沙特阿拉伯","中东","电网","https://www.se.com.sa/"),
    ("中国建筑肯尼亚医院项目主体封顶","中国建筑","official","肯尼亚","非洲","医疗建筑","https://www.cscec.com/"),
    ("某央企拟参与中东海水淡化项目","走出去情报","wechat_manual","沙特阿拉伯","中东","水务","https://mp.weixin.qq.com/"),
    ("AIIB 批准乌兹别克绿色输电项目","AIIB","official","乌兹别克斯坦","中亚","电网","https://www.aiib.org/en/projects/list/index.html"),
    ("越南北部工业园电子制造扩建","Vietnam Investment Review","media","越南","东南亚","电子制造","https://vir.com.vn/"),
    ("Masdar 与印尼合作开发漂浮式光伏","Masdar","official","印度尼西亚","东南亚","光伏储能","https://masdar.ae/"),
    ("EBRD 发布土耳其交通电气化咨询招标","EBRD","procurement","土耳其","欧洲","交通电气化","https://ecepp.ebrd.com/"),
    ("中工国际推进尼日利亚工业园电站","中工国际","official","尼日利亚","非洲","工业园","https://www.camce.com.cn/"),
    ("Siemens Energy 获卡塔尔电站服务合同","Siemens Energy","competitor","卡塔尔","中东","电力","https://www.siemens-energy.com/global/en/home/press-releases.html"),
    ("AfDB 更新坦桑尼亚电网采购计划","AfDB","procurement","坦桑尼亚","非洲","电网","https://www.afdb.org/en/projects-and-operations/procurement"),
    ("中车国际进入泰国轨交基地预审名单","Thailand BOI","procurement","泰国","东南亚","轨道交通","https://www.boi.go.th/"),
]
