export type Article = {
  id: number; title: string; summary: string; salesInsight: string; nextAction: string; category: string;
  sourceName: string; sourceType: string; reliability: "high" | "medium" | "low"; originalUrl: string;
  publishedAt: string; crawledAt: string; country: string; region: string; industry: string; kaNames: string[];
  matchedKeywords: string[]; productOpportunities: string[]; overseasEvidence: string; confidence: number;
  firstParty: boolean; verified: boolean;
};

const base = {
  crawledAt: "2026-07-17 11:38", firstParty: true, verified: true,
};

export const ARTICLES: Article[] = [
  { ...base, id:1, title:"中国电建签署沙特 1.8GW 光伏项目 EPC 合同", summary:"中国电建所属山东电建与项目业主签署沙特大型光伏电站 EPC 合同，工作范围覆盖升压站、送出线路及配套储能接口。", salesInsight:"项目进入工程设计与设备定标窗口，中压配电、保护控制与 SCADA 具备前置介入价值。", nextAction:"48 小时内联系山东电建沙特项目部，确认电气包技术规范与供应商短名单。", category:"KA 动态", sourceName:"中国电建", sourceType:"official", reliability:"high", originalUrl:"https://www.powerchina.cn/", publishedAt:"2026-07-17 09:20", country:"沙特阿拉伯", region:"中东", industry:"光伏新能源", kaNames:["中国电建"], matchedKeywords:["中国电建","山东电建","EPC"], productOpportunities:["中压开关设备","保护控制","SCADA","微电网"], overseasEvidence:"标题命中“沙特”“EPC 合同”；正文出现项目所在地与海外业主。", confidence:.96 },
  { ...base, id:2, title:"NEOM 公布新一批数据中心园区基础设施采购计划", summary:"NEOM 采购平台发布园区供配电、模块化数据中心与冷却基础设施市场征询，项目处于供应商预审阶段。", salesInsight:"预审阶段适合以完整数据中心电力链路方案切入，并联合本地集成商完成资质提交。", nextAction:"核对预审截止日，组织本地合作伙伴提交 UPS 与中低压配电业绩清单。", category:"招投标/采购", sourceName:"NEOM", sourceType:"procurement", reliability:"high", originalUrl:"https://www.neom.com/", publishedAt:"2026-07-17 08:15", country:"沙特阿拉伯", region:"中东", industry:"数据中心", kaNames:[], matchedKeywords:["NEOM","供应商预审"], productOpportunities:["UPS","中低压配电","能效管理","楼宇管理"], overseasEvidence:"来源为沙特 NEOM 官方平台，正文含数据中心园区位置。", confidence:.94 },
  { ...base, id:3, title:"中国能建葛洲坝中标越南 500kV 输变电工程", summary:"越南电力集团公告中国能建所属葛洲坝进入 500kV 输变电工程中标名单，合同待完成最终签署。", salesInsight:"输变电项目对中压成套、保护与自动化系统存在机会，但合同状态尚未最终生效。", nextAction:"向葛洲坝国际业务团队核实合同签署状态并获取一次系统图。", category:"市场项目", sourceName:"Vietnam Electricity", sourceType:"official", reliability:"high", originalUrl:"https://en.evn.com.vn/", publishedAt:"2026-07-16 18:40", country:"越南", region:"东南亚", industry:"电网", kaNames:["中国能建"], matchedKeywords:["中国能建","葛洲坝","500kV"], productOpportunities:["中压配电","保护控制","SCADA"], overseasEvidence:"越南业主 EVN 官方来源，命中越南项目地点。", confidence:.92 },
  { ...base, id:4, title:"墨西哥克雷塔罗新增超大规模数据中心投资计划", summary:"当地行业媒体报道，一家国际云服务商计划在克雷塔罗扩建数据中心园区，投资规模仍待企业官方确认。", salesInsight:"克雷塔罗是墨西哥数据中心高密度区域，可作为潜在线索纳入设计院与总包商地图。", nextAction:"通过项目所在地投资促进机构核验业主及环评文件，再决定账户跟进级别。", category:"产品机会", sourceName:"Mexico Business News", sourceType:"media", reliability:"medium", originalUrl:"https://mexicobusiness.news/", publishedAt:"2026-07-16 16:10", country:"墨西哥", region:"拉美", industry:"数据中心", kaNames:[], matchedKeywords:["数据中心","克雷塔罗"], productOpportunities:["UPS","中低压配电","楼宇管理"], overseasEvidence:"正文出现墨西哥克雷塔罗项目地点及美元投资表述。", confidence:.76, firstParty:false, verified:false },
  { ...base, id:5, title:"ADB 批准菲律宾岛屿微电网韧性提升项目融资", summary:"亚洲开发银行批准菲律宾偏远岛屿清洁能源与微电网项目融资，后续将分批发布咨询与设备采购。", salesInsight:"多边开发银行项目流程公开、付款风险较低，适合提前跟踪采购计划和实施机构。", nextAction:"订阅项目采购计划，识别储能、微网控制与配电包的预计招标月份。", category:"招投标/采购", sourceName:"Asian Development Bank", sourceType:"procurement", reliability:"high", originalUrl:"https://www.adb.org/projects/tenders", publishedAt:"2026-07-16 13:50", country:"菲律宾", region:"东南亚", industry:"微电网", kaNames:[], matchedKeywords:["ADB","菲律宾","微电网"], productOpportunities:["微电网控制","中低压配电","能效管理"], overseasEvidence:"ADB 官方项目页明确列示 Philippines 与项目编号。", confidence:.97 },
  { ...base, id:6, title:"ABB 在阿联酋发布新一代配电数字化解决方案", summary:"ABB 在阿联酋区域活动发布面向大型基础设施的数字化配电与状态监测方案。", salesInsight:"竞品强化本地数字化配电叙事，需对重点顾问与 EPC 更新施耐德差异化价值材料。", nextAction:"梳理阿联酋在跟项目竞品态势，向顾问客户推送 EcoStruxure 架构对比。", category:"竞争对手动态", sourceName:"ABB News", sourceType:"competitor", reliability:"high", originalUrl:"https://global.abb/group/en/media/news", publishedAt:"2026-07-16 11:20", country:"阿联酋", region:"中东", industry:"基础设施", kaNames:[], matchedKeywords:["ABB","阿联酋"], productOpportunities:["数字化配电","能效管理"], overseasEvidence:"ABB 官方新闻明确发布地点为 UAE。", confidence:.95 },
  { ...base, id:7, title:"中交集团承建印尼港口扩建项目进入机电安装阶段", summary:"中交集团官方披露印尼港口扩建项目土建主体完成，项目进入机电与自动化系统安装阶段。", salesInsight:"机电安装是低压配电、港机供电与能源管理的关键定标期。", nextAction:"联系项目机电负责人核对 MCC、低压柜及岸电系统供货边界。", category:"KA 动态", sourceName:"中交集团", sourceType:"official", reliability:"high", originalUrl:"https://www.ccccltd.cn/", publishedAt:"2026-07-15 17:30", country:"印度尼西亚", region:"东南亚", industry:"港口", kaNames:["中交集团"], matchedKeywords:["中交集团","印尼","机电安装"], productOpportunities:["低压配电","自动化","能源管理"], overseasEvidence:"官方标题与正文命中“印尼港口”。", confidence:.96 },
  { ...base, id:8, title:"世界银行发布埃及配电网现代化项目采购预告", summary:"世界银行项目文件列出埃及配电网自动化、智能环网柜和控制中心升级采购包。", salesInsight:"采购包与施耐德配电自动化能力高度匹配，项目文件可用于定位实施机构与顾问。", nextAction:"下载采购计划并建立包件时间表，提前对接埃及电力控股及设计顾问。", category:"招投标/采购", sourceName:"World Bank", sourceType:"procurement", reliability:"high", originalUrl:"https://projects.worldbank.org/en/projects-operations/procurement", publishedAt:"2026-07-15 14:12", country:"埃及", region:"非洲", industry:"电网", kaNames:[], matchedKeywords:["World Bank","埃及","配电网"], productOpportunities:["环网柜","保护控制","SCADA"], overseasEvidence:"世界银行官方采购文件列示 Egypt。", confidence:.98 },
  { ...base, id:9, title:"中国铁建国际签约马来西亚城市轨道交通配套工程", summary:"中国铁建国际与当地业主签署城市轨道交通配套工程协议，范围包括车站机电与供电接口。", salesInsight:"轨交车站涉及配电、楼宇自控、能源管理及 UPS，适合在设计深化前进入技术交流。", nextAction:"与铁建国际项目团队安排轨交供配电方案交流，确认业主指定品牌要求。", category:"市场项目", sourceName:"中国铁建", sourceType:"official", reliability:"high", originalUrl:"https://www.crcc.cn/", publishedAt:"2026-07-15 10:05", country:"马来西亚", region:"东南亚", industry:"轨道交通", kaNames:["中国铁建"], matchedKeywords:["中国铁建","铁建国际","马来西亚"], productOpportunities:["中低压配电","楼宇自控","UPS"], overseasEvidence:"官方新闻出现马来西亚项目地点和国际业务主体。", confidence:.95 },
  { ...base, id:10, title:"沙特电力公司启动新一轮变电站框架供应商注册", summary:"沙特电力公司供应商平台更新变电站设备框架注册要求，覆盖中压开关、继保和站控系统。", salesInsight:"注册窗口决定后续框架招标参与资格，应同步校验本地化与型式试验文件。", nextAction:"由沙特团队完成供应商资质差距清单，并确认本地合作伙伴投标路径。", category:"招投标/采购", sourceName:"Saudi Electricity Company", sourceType:"official", reliability:"high", originalUrl:"https://www.se.com.sa/", publishedAt:"2026-07-14 19:00", country:"沙特阿拉伯", region:"中东", industry:"电网", kaNames:[], matchedKeywords:["SEC","供应商注册"], productOpportunities:["中压开关设备","保护控制","SCADA"], overseasEvidence:"沙特电力公司官方供应商平台。", confidence:.98 },
  { ...base, id:11, title:"中国建筑海外医院项目在非洲完成主体封顶", summary:"中国建筑披露东非医院项目主体封顶，下一阶段将转入机电安装与医疗配套施工。", salesInsight:"医院机电阶段可切入配电可靠性、楼宇控制、UPS 与能源管理。", nextAction:"向中建海外项目商务经理获取机电分包计划与设备送审节点。", category:"KA 动态", sourceName:"中国建筑", sourceType:"official", reliability:"high", originalUrl:"https://www.cscec.com/", publishedAt:"2026-07-14 16:20", country:"肯尼亚", region:"非洲", industry:"医疗建筑", kaNames:["中国建筑"], matchedKeywords:["中国建筑","海外医院","肯尼亚"], productOpportunities:["低压配电","楼宇自控","UPS","能源管理"], overseasEvidence:"官网正文明确肯尼亚项目位置。", confidence:.93 },
  { ...base, id:12, title:"走出去情报：某央企拟参与中东海水淡化项目", summary:"公众号文章称某央企正评估中东海水淡化项目，但未提供业主公告或可核验的项目编号。", salesInsight:"可作为早期关系线索，不应据此确认项目或合同事实。", nextAction:"优先在 SWCC、业主采购平台及央企官网交叉核验后再进入销售漏斗。", category:"媒体线索", sourceName:"走出去情报", sourceType:"wechat_manual", reliability:"low", originalUrl:"https://mp.weixin.qq.com/", publishedAt:"2026-07-14 12:15", country:"沙特阿拉伯", region:"中东", industry:"水务", kaNames:["中国能建"], matchedKeywords:["央企","海水淡化"], productOpportunities:["中低压配电","自动化","过程控制"], overseasEvidence:"手动导入正文命中“中东”“海水淡化”；未发现官方项目编号。", confidence:.54, firstParty:false, verified:false },
  { ...base, id:13, title:"AIIB 批准乌兹别克斯坦绿色输电走廊项目", summary:"亚投行批准乌兹别克斯坦绿色输电走廊融资，项目包含变电站升级和可再生能源并网。", salesInsight:"融资批准后将进入实施与采购准备期，可围绕保护控制和数字化变电站建立追踪。", nextAction:"锁定实施机构与采购代理，建立项目联系人和关键节点。", category:"政策与融资", sourceName:"AIIB", sourceType:"official", reliability:"high", originalUrl:"https://www.aiib.org/en/projects/list/index.html", publishedAt:"2026-07-13 15:40", country:"乌兹别克斯坦", region:"中亚", industry:"电网", kaNames:[], matchedKeywords:["AIIB","乌兹别克斯坦"], productOpportunities:["中压配电","保护控制","SCADA"], overseasEvidence:"AIIB 官方项目页明确项目国别。", confidence:.97 },
  { ...base, id:14, title:"越南北部工业园批准新一轮电子制造扩建", summary:"越南投资主管部门批准北部工业园电子制造工厂扩建，项目将新增洁净厂房和公用工程系统。", salesInsight:"电子制造扩建通常带来高可靠配电、自动化、能效与电能质量需求。", nextAction:"通过园区运营方确认总包与设计单位，安排工厂数字化配电方案交流。", category:"市场项目", sourceName:"Vietnam Investment Review", sourceType:"media", reliability:"medium", originalUrl:"https://vir.com.vn/", publishedAt:"2026-07-13 11:35", country:"越南", region:"东南亚", industry:"电子制造", kaNames:[], matchedKeywords:["越南","工业园","扩建"], productOpportunities:["配电","自动化","能效管理","工业软件"], overseasEvidence:"正文明确越南北部工业园。", confidence:.79, firstParty:false, verified:false },
  { ...base, id:15, title:"Masdar 与印尼合作开发漂浮式光伏及储能", summary:"Masdar 官方宣布与印尼合作伙伴签署漂浮式光伏及储能开发协议，项目进入可研阶段。", salesInsight:"可研阶段适合影响储能接口、微网控制与升压站技术路线。", nextAction:"联系 Masdar 账户团队确认 EPC 选择节奏和技术顾问。", category:"合作伙伴动态", sourceName:"Masdar", sourceType:"official", reliability:"high", originalUrl:"https://masdar.ae/", publishedAt:"2026-07-12 18:05", country:"印度尼西亚", region:"东南亚", industry:"光伏储能", kaNames:[], matchedKeywords:["Masdar","印尼","储能"], productOpportunities:["微电网","中压配电","能效管理"], overseasEvidence:"Masdar 官方公告明确 Indonesia。", confidence:.96 },
  { ...base, id:16, title:"EBRD 发布土耳其城市交通电气化咨询招标", summary:"EBRD 采购平台发布城市公交电气化和充电基础设施咨询服务招标。", salesInsight:"咨询阶段可影响后续充电配电架构与能源管理技术规范。", nextAction:"识别中标顾问并准备车队充电与微网参考方案。", category:"招投标/采购", sourceName:"EBRD Procurement", sourceType:"procurement", reliability:"high", originalUrl:"https://ecepp.ebrd.com/", publishedAt:"2026-07-12 09:30", country:"土耳其", region:"欧洲", industry:"交通电气化", kaNames:[], matchedKeywords:["EBRD","Turkey"], productOpportunities:["中低压配电","能源管理","微电网"], overseasEvidence:"EBRD 招标文件列示 Türkiye。", confidence:.98 },
  { ...base, id:17, title:"国机中工国际推进尼日利亚工业园配套电站", summary:"中工国际披露尼日利亚工业园配套电站完成初步设计审查，计划进入设备采购。", salesInsight:"设备采购前是配电与自动化技术澄清的关键窗口。", nextAction:"联系中工国际项目采购负责人，提交电站电气系统参考清单。", category:"KA 动态", sourceName:"中工国际", sourceType:"official", reliability:"high", originalUrl:"https://www.camce.com.cn/", publishedAt:"2026-07-11 17:20", country:"尼日利亚", region:"非洲", industry:"工业园", kaNames:["国机"], matchedKeywords:["中工国际","尼日利亚"], productOpportunities:["配电","自动化","能效管理"], overseasEvidence:"企业官网明确尼日利亚项目地点。", confidence:.94 },
  { ...base, id:18, title:"Siemens Energy 获卡塔尔燃机电站长期服务合同", summary:"Siemens Energy 宣布获得卡塔尔燃机电站长期服务合同，覆盖设备维护与数字化服务。", salesInsight:"竞品深化业主长期服务关系，需评估项目配电与能源管理领域的协同或防守策略。", nextAction:"更新 QatarEnergy 账户地图，核查站内低压与自动化系统存量。", category:"竞争对手动态", sourceName:"Siemens Energy", sourceType:"competitor", reliability:"high", originalUrl:"https://www.siemens-energy.com/global/en/home/press-releases.html", publishedAt:"2026-07-11 13:45", country:"卡塔尔", region:"中东", industry:"电力", kaNames:[], matchedKeywords:["Siemens Energy","Qatar"], productOpportunities:["低压配电","能源管理","自动化"], overseasEvidence:"竞争对手官方公告明确 Qatar。", confidence:.96 },
  { ...base, id:19, title:"非洲开发银行更新坦桑尼亚电网互联项目采购计划", summary:"非洲开发银行更新坦桑尼亚跨区输电项目采购计划，新增变电站控制与通信包。", salesInsight:"采购计划更新提供明确包件与时间节点，适合建立投标伙伴组合。", nextAction:"下载最新 GPN，确认设备原产地条款与投标截止日。", category:"招投标/采购", sourceName:"African Development Bank", sourceType:"procurement", reliability:"high", originalUrl:"https://www.afdb.org/en/projects-and-operations/procurement", publishedAt:"2026-07-10 16:00", country:"坦桑尼亚", region:"非洲", industry:"电网", kaNames:[], matchedKeywords:["AfDB","Tanzania"], productOpportunities:["保护控制","SCADA","中压配电"], overseasEvidence:"AfDB 官方采购计划列示 Tanzania。", confidence:.98 },
  { ...base, id:20, title:"中车国际进入泰国轨道车辆基地预审名单", summary:"泰国采购机构公布轨道车辆维修基地项目预审结果，中车国际进入后续资格评估。", salesInsight:"车辆基地对配电、车间自动化、楼宇管理与能源监控有集成机会。", nextAction:"与中车国际东南亚团队核实总包边界并识别基地机电顾问。", category:"市场项目", sourceName:"Thailand Procurement", sourceType:"procurement", reliability:"high", originalUrl:"https://www.boi.go.th/", publishedAt:"2026-07-10 10:20", country:"泰国", region:"东南亚", industry:"轨道交通", kaNames:["中车国际"], matchedKeywords:["中车国际","泰国","预审"], productOpportunities:["配电","自动化","楼宇管理"], overseasEvidence:"官方预审文件列示 Thailand 与中车国际。", confidence:.91 },
];

export const COUNTRY_STATS = [
  {name:"沙特",value:38},{name:"越南",value:31},{name:"印尼",value:28},{name:"阿联酋",value:24},{name:"埃及",value:22},{name:"马来西亚",value:20},{name:"墨西哥",value:18},{name:"菲律宾",value:16},{name:"泰国",value:14},{name:"尼日利亚",value:13},{name:"卡塔尔",value:11},{name:"肯尼亚",value:10},{name:"土耳其",value:9},{name:"乌兹别克",value:8},{name:"坦桑尼亚",value:7},
];
export const REGION_STATS = [{name:"东南亚",value:86},{name:"中东",value:79},{name:"非洲",value:54},{name:"拉美",value:31},{name:"中亚",value:22},{name:"欧洲",value:18},{name:"南亚",value:13}];
