"use client";

import { FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { api, API_BASE_VALID, AUTH_EXPIRED_EVENT, clearSession, hasSession, login, logout, type SessionUser } from "./api-client";

type Article = {
  id:string; title:string; original_title:string; summary:string; sales_insight:string; original_url:string;
  source_name:string; source_type:string; reliability_level:"high"|"medium"|"low"; published_at:string|null; fetched_at:string;
  country:string|null; region:string|null; ka:string[]; matched_entities:string[]; ka_candidates:{ka_group:string;matched_entity:string;confidence:number;needs_review:boolean}[];
  industries:string[]; intelligence_types:string[]; project_type:string|null; project_stage:string|null; confidence_score:number;
  verification_status:string; review_status:string; cross_source_count:number; date_verification_status:string;
  canonical_event_id:string|null; verification_notice?:string|null; favorite:boolean; read:boolean;
  supporting_sources?:{source_id:string;title:string;original_url:string;published_at:string|null;reliability_level:string;is_primary:boolean;source_role:string;consistency_status:string}[];
  canonical_event?:{id:string;title:string;event_type:string|null;source_count:number;official_source_count:number;verification_status:string;conflict_status:string}|null;
};
type Source = {
  id:string;source_name:string;source_url:string;source_type:string;reliability_level:string;crawl_method:string;adapter_status:string;
  entity_id?:string|null;
  enabled:boolean;region_focus:string[];country_focus:string[];industry_focus:string[];last_success_at:string|null;last_failure_at:string|null;
  latest_fetched_count:number;latest_new_count:number;latest_updated_count:number;latest_duplicate_count:number;latest_skipped_count:number;
  latest_status:string;latest_failure_reason:string|null;backfill_enabled:boolean;backfill_status:string;
  backfill_page_limit:number;backfill_cursor:string|null;last_backfill_at:string|null;
};
type Status={last_successful_update:string|null;is_updating:boolean;running_count:number;failed_source_count:number;delay_status:string};
type Stats={
  counting_basis:string;date_from:string;date_to:string;year_intelligence_count:number;recent_30_count:number;new_factory_count:number;
  data_center_count:number;rail_transit_count:number;power_energy_count:number;international_policy_count:number;tax_investment_policy_count:number;
  ka_intelligence_count:number;high_reliability_ratio:number;cross_verified_ratio:number;pending_review_count:number;failed_source_count:number;
  year_covered_source_count:number;backfill_completed_source_count:number;backfill_pending_source_count:number;backfill_unsupported_source_count:number;
  countries:{name:string;value:number}[];regions:{name:string;value:number}[];
};
type KAGroup={id:string;name:string;ka_type:string;entities:{id:string;name:string;entity_relation:string;is_verified_relation:boolean}[]};
type Batch={id:string;created_by:string;created_at:string;started_at:string|null;finished_at:string|null;status:string;total_sources:number;completed:number;success:number;empty:number;failed:number;skipped:number;new_count:number;updated_count:number;duplicate_count:number;current_sources:string[];remaining:number;cancel_requested:boolean;items?:{id:string;source_name:string;status:string;skip_reason:string|null;failure_reason:string|null}[]};
type Backfill={id:string;source_id:string;source_name:string;status:string;date_from:string;date_to:string;page_limit:number;current_page:number;fetched_count:number;new_count:number;duplicate_count:number;date_unverified_count:number;failure_reason:string|null;created_at:string};
type PolicyItem=Article&{policy:{
  publishing_country:string|null;affected_countries:string[];issuing_body:string|null;policy_types:string[];
  applicable_industries:string[];effective_date:string|null;expiry_date:string|null;tax_type:string|null;
  tax_rate_change:string|null;investment_threshold:string|null;foreign_ownership_ratio:string|null;
  localization_requirements:string[];local_procurement_ratio:string|null;incentives:string[];
  import_tariff:string|null;export_controls:string[];technical_standards:string[];
  certification_requirements:string[];china_company_impact:string|null;schneider_sales_impact:string|null;
  verification_items:string[];
}};
type CSCECEntity={entity_id:string;canonical_name:string;short_name:string|null;aliases:string[];parent_entity_id:string|null;entity_level:string;entity_type:string;stock_code:string|null;official_url:string|null;country:string|null;region:string|null;overseas:boolean;verification_status:string;verification_source:string|null;active:boolean;notes:string;updated_at:string};
type CSCECLeadership={id:string;person_name:string|null;entity_id:string|null;parent_entity_id:string|null;title_before:string|null;title_after:string|null;appointment_type:string;effective_date:string|null;published_at:string|null;source_url:string;source_name:string;evidence_excerpt:string;confidence:number;verification_status:string;counterparty:string|null;country:string|null;region:string|null;location_scope:string};
type CSCECOrg={id:string;change_type:string;display_title:string;entity_before:string|null;entity_after:string|null;parent_before:string|null;parent_after:string|null;effective_date:string|null;published_at:string|null;source_urls:string[];source_count:number;evidence_excerpt:string;confidence:number;verification_status:string};

const NAV=[
  ["dashboard","总览"],["intelligence","全部情报"],["market","市场与行业机会"],["opportunities","国家与区域机会"],
  ["policies","政策情报"],["ka","KA动态"],["competitors","竞争对手动态"],["chambers","商协会动态"],
  ["sources","数据源管理"],["batches","抓取批次"],["backfills","历史回填"],["review","人工审核"],
  ["cscec","中建KA动态"],
] as const;
const ROLE_LEVEL={viewer:0,sales:1,analyst:2,admin:3};
const TYPE_LABELS:Record<string,string>={market_project:"市场项目",new_factory:"新建工厂",data_center:"数据中心",rail_transit:"轨道交通",power_grid:"电网输配电",renewable_energy:"新能源",energy_storage:"储能",industrial_park:"工业园区",manufacturing:"制造业",building_infrastructure:"公共基础设施",oil_gas_chemical:"油气化工",mining_metals:"矿业冶金",international_policy:"国际政策",tax_policy:"税收政策",investment_policy:"投资政策",foreign_access:"外资准入",localization_policy:"本地化",trade_tariff:"关税与贸易",standards_compliance:"标准合规",outbound_china_policy:"中国企业出海政策",ka_leader:"KA领导人动态",ka_company:"KA公司动态",competitor:"竞争对手",chamber_association:"商协会"};
const CSCEC_EVENT_LABELS:Record<string,string>={resignation:"辞任",retirement:"退休",removal:"免职",transfer:"调任",concurrent_role:"兼任",board_change:"董事会变动",appointment:"任命",overseas_visit:"海外访问",inspection:"调研考察",meeting:"会议活动",signing:"签约活动",strategy_activity:"战略活动"};
const oneYearAgo=()=>{const d=new Date();d.setUTCDate(d.getUTCDate()-365);return d.toISOString().slice(0,10)};
const fmt=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short",timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(new Date(value)):"待核验";
const pct=(v:number)=>`${Math.round(v*100)}%`;

function Login({onSuccess,notice,checking=false}:{onSuccess:(u:SessionUser)=>void;notice?:string;checking?:boolean}){
  const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{onSuccess(await login(email,password))}catch(err){setError(err instanceof Error?err.message:"登录失败")}finally{setBusy(false)}};
  return <div className="login-page"><section className="login-brand"><span className="brand-mark big">SE</span><p>SCHNEIDER ELECTRIC</p><h1>海外销售情报工作台</h1><span>可信来源 · 一年期情报 · 可追溯销售线索</span></section><form className="login-card" onSubmit={submit}><small className="eyebrow">SECURE WORKSPACE</small><h2>登录工作台</h2><p>使用管理员创建的团队账号继续。</p><small className="login-release">前端版本：连接保护 v2</small>{checking&&<div className="login-status">正在验证已有登录会话，您也可以直接重新登录。</div>}{!API_BASE_VALID&&<div className="login-error">部署尚未配置有效的 API 地址。</div>}{notice&&<div className="login-error">{notice}</div>}{error&&<div className="login-error">{error}</div>}<label>工作邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="btn primary login-submit" disabled={busy||!API_BASE_VALID}>{busy?"登录中…":"登录"}</button><small>连续 5 次登录失败将锁定账号 15 分钟。</small></form></div>;
}

function Metric({label,value,note}:{label:string;value:string|number;note?:string}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"good"|"warn"|"bad"|"neutral"}){return <span className={`badge ${tone}`}>{children}</span>}

function ArticleList({items,onOpen,empty="当前筛选没有真实数据"}:{items:Article[];onOpen:(a:Article)=>void;empty?:string}){
  if(!items.length)return <div className="empty-state"><b>{empty}</b><p>请调整筛选条件，或等待对应来源完成抓取与核验。</p></div>;
  return <div className="article-list">{items.map(a=><button className={`article-row ${a.read?"is-read":""}`} key={a.id} onClick={()=>onOpen(a)}><div className="score"><strong>{Math.round(a.confidence_score*100)}</strong><span>置信度</span></div><div className="article-main"><div className="article-meta"><Badge tone={a.reliability_level==="high"?"good":a.reliability_level==="low"?"bad":"warn"}>{a.reliability_level==="high"?"高可信":a.reliability_level==="medium"?"中可信":"低可信"}</Badge>{a.intelligence_types.slice(0,2).map(t=><Badge key={t}>{TYPE_LABELS[t]||t}</Badge>)}<span>{a.country||a.region||"地点待核验"}</span><span>{fmt(a.published_at)}</span></div><h3>{a.original_title||a.title}</h3><p>{a.summary||"尚无可核验摘要"}</p><small>{a.source_name} · {a.cross_source_count>1?`${a.cross_source_count} 个来源交叉关联`:"单一来源"}</small></div><span className="row-arrow">›</span></button>)}</div>;
}

function Dashboard({stats,status,onCountry,navigate}:{stats:Stats|null;status:Status|null;onCountry:(c:string)=>void;navigate:(v:string)=>void}){
  const [top,setTop]=useState<"10"|"20"|"all">("10");const countries=(stats?.countries||[]).slice(0,top==="all"?undefined:Number(top));const max=Math.max(1,...countries.map(x=>x.value));
  return <><div className="page-title"><div><small className="eyebrow">ONE-YEAR GLOBAL INTELLIGENCE</small><h1>最近一年销售情报总览</h1><p>{stats?.counting_basis||"正在读取数据库统计口径"}</p></div><span className="fresh">统计区间 {stats?`${fmt(stats.date_from)} — ${fmt(stats.date_to)}`:"—"}</span></div><div className="metrics"><Metric label="最近一年情报" value={stats?.year_intelligence_count??"—"} note="按事件级去重"/><Metric label="最近30天新增" value={stats?.recent_30_count??"—"}/><Metric label="新建工厂" value={stats?.new_factory_count??"—"}/><Metric label="数据中心" value={stats?.data_center_count??"—"}/><Metric label="轨道交通" value={stats?.rail_transit_count??"—"}/><Metric label="电力与能源" value={stats?.power_energy_count??"—"}/></div><div className="dashboard-grid"><section className="panel span2"><div className="panel-head"><div><h2>国家项目热度</h2><p>最近365天 canonical event，点击国家进入对应机会</p></div><div className="segmented">{(["10","20","all"] as const).map(x=><button key={x} className={top===x?"active":""} onClick={()=>setTop(x)}>{x==="all"?"全部":`Top ${x}`}</button>)}</div></div><div className="horizontal-chart">{countries.map(x=><button key={x.name} title={x.name} onClick={()=>onCountry(x.name)}><span>{x.name}</span><i><em style={{width:`${Math.max(3,x.value/max*100)}%`}}/></i><strong>{x.value}</strong></button>)}</div></section><section className="panel"><div className="panel-head"><div><h2>情报质量</h2><p>来源与交叉验证</p></div></div><div className="quality-cards"><Metric label="高可信一手来源" value={stats?pct(stats.high_reliability_ratio):"—"}/><Metric label="已交叉验证" value={stats?pct(stats.cross_verified_ratio):"—"}/><Metric label="待人工核验" value={stats?.pending_review_count??"—"}/><Metric label="失败来源" value={stats?.failed_source_count??status?.failed_source_count??"—"}/></div></section></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>历史回填覆盖</h2><p>不将未完成回填描述为完整一年覆盖</p></div></div><div className="quality-cards"><Metric label="一年覆盖来源" value={stats?.year_covered_source_count??"—"}/><Metric label="已完成回填" value={stats?.backfill_completed_source_count??"—"}/><Metric label="回填进行/待执行" value={stats?.backfill_pending_source_count??"—"}/><Metric label="暂不支持回填" value={stats?.backfill_unsupported_source_count??"—"}/></div><button className="text-link" onClick={()=>navigate("backfills")}>查看真实回填状态 →</button></section><section className="panel span2"><div className="panel-head"><div><h2>重点情报</h2><p>数据库实时计数</p></div></div><div className="focus-grid"><Metric label="国际政策" value={stats?.international_policy_count??"—"}/><Metric label="税收与投资政策" value={stats?.tax_investment_policy_count??"—"}/><Metric label="KA动态" value={stats?.ka_intelligence_count??"—"}/></div></section></div></>;
}

function FeedPage({title,subtitle,items,loading,onOpen,onSearch,kind}:{title:string;subtitle:string;items:Article[];loading:boolean;onOpen:(a:Article)=>void;onSearch:(q:string,reliability:string,type?:string)=>void;kind?:string}){
  const [q,setQ]=useState("");const [reliability,setReliability]=useState("");const [type,setType]=useState(kind||"");
  return <><div className="page-title"><div><small className="eyebrow">TRACEABLE INTELLIGENCE</small><h1>{title}</h1><p>{subtitle}</p></div></div><div className="filterbar"><label className="search-field">⌕<input placeholder="搜索项目、企业、国家或政策" value={q} onChange={e=>setQ(e.target.value)}/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="">全部情报类型</option>{Object.entries(TYPE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={reliability} onChange={e=>setReliability(e.target.value)}><option value="">全部可信度</option><option value="high">高可信</option><option value="medium">中可信</option><option value="low">低可信</option></select><button className="btn" onClick={()=>onSearch(q,reliability,type)}>{loading?"查询中…":"应用筛选"}</button></div><section className="list-panel"><div className="list-head"><b>最近365天结果</b><span>{items.length} 条当前页记录</span></div><ArticleList items={items} onOpen={onOpen}/></section></>;
}

function PolicyPage({onOpen}:{onOpen:(a:Article)=>void}){
  const [items,setItems]=useState<PolicyItem[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const [country,setCountry]=useState("");const [policyType,setPolicyType]=useState("");const [reliability,setReliability]=useState("");
  const [dateFrom,setDateFrom]=useState(oneYearAgo());const [dateTo,setDateTo]=useState(new Date().toISOString().slice(0,10));
  const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams({date_from:dateFrom,date_to:dateTo,page_size:"200"});if(country)p.set("country",country);if(policyType)p.set("policy_type",policyType);if(reliability)p.set("reliability",reliability);const data=await api<{items:PolicyItem[]}>(`/api/policies?${p}`);setItems(data.items)}catch(e){setError(e instanceof Error?e.message:"政策情报加载失败")}finally{setLoading(false)}},[country,policyType,reliability,dateFrom,dateTo]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  return <><div className="page-title"><div><small className="eyebrow">POLICY INTELLIGENCE</small><h1>政策情报</h1><p>按发布国、受影响国家、政策类型、税率、准入、本地化、标准认证与销售影响查看。</p></div></div><div className="filterbar"><input value={country} onChange={e=>setCountry(e.target.value)} placeholder="发布国或受影响国家"/><select value={policyType} onChange={e=>setPolicyType(e.target.value)}><option value="">全部政策维度</option>{["international_policy","tax_policy","investment_policy","foreign_access","localization_policy","trade_tariff","standards_compliance","outbound_china_policy"].map(x=><option key={x} value={x}>{TYPE_LABELS[x]}</option>)}</select><select value={reliability} onChange={e=>setReliability(e.target.value)}><option value="">全部可信度</option><option value="high">高可信</option><option value="medium">中可信</option><option value="low">低可信</option></select><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/><button className="btn" onClick={()=>void load()} disabled={loading}>{loading?"查询中…":"应用筛选"}</button></div>{error&&<div className="verification-alert"><b>{error}</b></div>}<section className="policy-grid">{items.map(item=><button className="policy-card" key={item.id} onClick={()=>onOpen(item)}><div className="article-meta"><Badge tone={item.reliability_level==="high"?"good":item.reliability_level==="low"?"bad":"warn"}>{item.reliability_level} 可信</Badge>{item.policy.policy_types.map(x=><Badge key={x}>{TYPE_LABELS[x]||x}</Badge>)}</div><h3>{item.original_title||item.title}</h3><p>{item.summary}</p><dl><div><dt>发布机构</dt><dd>{item.policy.issuing_body||item.source_name}</dd></div><div><dt>发布国 / 影响国家</dt><dd>{item.policy.publishing_country||"待核验"} / {item.policy.affected_countries.join("、")||"待核验"}</dd></div><div><dt>税率 / 投资门槛</dt><dd>{item.policy.tax_rate_change||item.policy.import_tariff||"—"} / {item.policy.investment_threshold||"—"}</dd></div><div><dt>外资比例 / 本地采购</dt><dd>{item.policy.foreign_ownership_ratio||"—"} / {item.policy.local_procurement_ratio||"—"}</dd></div><div><dt>本地化与认证</dt><dd>{[...item.policy.localization_requirements,...item.policy.certification_requirements].join("、")||"—"}</dd></div><div><dt>施耐德销售影响</dt><dd>{item.policy.schneider_sales_impact||"待分析"}</dd></div></dl><small>{fmt(item.published_at)} · {item.source_name}</small></button>)}</section>{!loading&&!items.length&&<div className="empty-state"><b>当前筛选没有已结构化的政策情报</b><p>不会用演示数据填充空白。</p></div>}</>;
}

function Opportunities({stats,articles,initialCountry,onCountry,onOpen}:{stats:Stats|null;articles:Article[];initialCountry:string;onCountry:(c:string)=>void;onOpen:(a:Article)=>void}){
  const [dimension,setDimension]=useState<"country"|"region">("country");const [region,setRegion]=useState("");const [country,setCountry]=useState(initialCountry);const [items,setItems]=useState<Article[]>(articles);const [loading,setLoading]=useState(false);const [dateFrom,setDateFrom]=useState(oneYearAgo());const [dateTo,setDateTo]=useState(new Date().toISOString().slice(0,10));
  const load=useCallback(async(nextCountry=country,nextRegion=region)=>{setLoading(true);try{const p=new URLSearchParams({date_from:dateFrom,date_to:dateTo,page_size:"200"});if(nextCountry)p.set("country",nextCountry);if(nextRegion)p.set("region",nextRegion);const data=await api<{items:Article[]}>(`/api/opportunities?${p}`);setItems(data.items)}finally{setLoading(false)}},[country,region,dateFrom,dateTo]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  const regions=stats?.regions||[];const countries=stats?.countries||[];
  return <><div className="page-title"><div><small className="eyebrow">MARKET GEOGRAPHY</small><h1>国家与区域机会</h1><p>国家和区域已合并；项目数量按 canonical event 统计，列表直接查询机会接口。</p></div></div><div className="filterbar"><div className="segmented"><button className={dimension==="country"?"active":""} onClick={()=>setDimension("country")}>国家</button><button className={dimension==="region"?"active":""} onClick={()=>setDimension("region")}>区域</button></div><select value={region} onChange={e=>{setRegion(e.target.value);setCountry("")}}><option value="">全部区域</option>{regions.map(x=><option key={x.name}>{x.name}</option>)}</select><select value={country} onChange={e=>{setCountry(e.target.value);if(e.target.value)onCountry(e.target.value)}}><option value="">全部国家</option>{countries.map(x=><option key={x.name}>{x.name}</option>)}</select><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} aria-label="开始日期"/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} aria-label="结束日期"/><button className="btn" onClick={()=>void load()} disabled={loading}>{loading?"查询中…":"应用筛选"}</button></div><div className="opportunity-layout"><aside className="rank-menu">{(dimension==="country"?countries:regions).map((x,i)=><button key={x.name} className={(dimension==="country"?country:region)===x.name?"active":""} onClick={()=>{if(dimension==="country"){setCountry(x.name);onCountry(x.name);void load(x.name,region)}else{setRegion(x.name);setCountry("");void load("",x.name)}}}><span>{String(i+1).padStart(2,"0")}</span><b title={x.name}>{x.name}</b><em>{x.value} 个事件</em></button>)}</aside><section className="list-panel"><div className="list-head"><b>{country||region||"全球"}机会</b><span>项目、政策、KA与原始来源联动</span></div><ArticleList items={items} onOpen={onOpen}/></section></div></>;
}

function KAPage({groups,onOpen}:{groups:KAGroup[];onOpen:(a:Article)=>void}){
  const [group,setGroup]=useState("");const [entity,setEntity]=useState("");const [type,setType]=useState("");const [items,setItems]=useState<Article[]>([]);const [leaders,setLeaders]=useState<{id:string;person_name:string|null;person_title:string|null;ka_group:string|null;action_type:string|null;factual_summary:string;source_url:string;published_at:string|null;confidence:number}[]>([]);const [loading,setLoading]=useState(false);
  const selected=groups.find(x=>x.name===group);
  const load=useCallback(async()=>{setLoading(true);try{const p=new URLSearchParams();if(group)p.set("ka_group",group);if(entity)p.set("matched_entity",entity);if(type)p.set("intelligence_type",type);const data=await api<{items:Article[];leaders:typeof leaders}>(`/api/ka-intelligence?${p}`);setItems(data.items);setLeaders(data.leaders)}finally{setLoading(false)}},[group,entity,type]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  return <><div className="page-title"><div><small className="eyebrow">KEY ACCOUNT INTELLIGENCE</small><h1>KA动态</h1><p>先选择KA业务组，再联动关联实体；业务映射不等同于已核验股权关系。</p></div></div><div className="filterbar"><select value={group} onChange={e=>{setGroup(e.target.value);setEntity("")}}><option value="">全部KA</option>{groups.map(x=><option key={x.id}>{x.name}</option>)}</select><select value={entity} onChange={e=>setEntity(e.target.value)} disabled={!group}><option value="">全部关联实体</option>{selected?.entities.map(x=><option key={x.id}>{x.name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="">领导人和公司动态</option><option value="ka_leader">领导人动态</option><option value="ka_company">公司动态</option><option value="market_project">海外项目</option></select><button className="btn" onClick={()=>void load()}>{loading?"查询中…":"查询"}</button></div>{leaders.length>0&&<section className="panel leader-timeline"><div className="panel-head"><div><h2>公开职业动态</h2><p>不采集私人联系方式、家庭信息或非公开个人信息</p></div></div>{leaders.slice(0,8).map(x=><a href={x.source_url} target="_blank" rel="noreferrer" key={x.id}><time>{fmt(x.published_at)}</time><b>{x.person_name||"姓名待核验"} · {x.person_title||x.action_type||"职业动态"}</b><span>{x.factual_summary}</span><em>{Math.round(x.confidence*100)}% 置信度</em></a>)}</section>}<section className="list-panel"><div className="list-head"><b>最近一年KA资讯时间线</b><span>{items.length} 条</span></div><ArticleList items={items} onOpen={onOpen}/></section></>;
}

function CSCECPage({user,onOpen,sources}:{user:SessionUser;onOpen:(a:Article)=>void;sources:Source[]}){
  const [tab,setTab]=useState<"events"|"leadership"|"organization"|"entities">("events");
  const [entities,setEntities]=useState<CSCECEntity[]>([]);
  const [events,setEvents]=useState<Article[]>([]);
  const [leadership,setLeadership]=useState<CSCECLeadership[]>([]);
  const [organization,setOrganization]=useState<CSCECOrg[]>([]);
  const [entityId,setEntityId]=useState("");
  const [loading,setLoading]=useState(false);
  const [message,setMessage]=useState("");
  const load=useCallback(async()=>{
    setLoading(true);setMessage("");
    try{
      const entityQuery=entityId?`?entity_id=${encodeURIComponent(entityId)}`:"";
      const [entityData,eventData,leaderData,orgData]=await Promise.all([
        api<{items:CSCECEntity[]}>("/api/ka/cscec/entities?active=true"),
        api<{items:Article[]}>(`/api/ka/cscec/events${entityQuery}`),
        api<CSCECLeadership[]>(`/api/ka/cscec/leadership-events${entityQuery}`),
        api<CSCECOrg[]>("/api/ka/cscec/org-events"),
      ]);
      setEntities(entityData.items);setEvents(eventData.items);setLeadership(leaderData);setOrganization(orgData);
    }catch(error){setMessage(error instanceof Error?error.message:"中建监测数据加载失败")}
    finally{setLoading(false)}
  },[entityId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  const adminAction=async(path:string,body:object={})=>{
    setLoading(true);setMessage("");
    try{const result=await api<{task_id?:string;id?:string;queued?:unknown[]}>(path,{method:"POST",body:JSON.stringify(body)});setMessage(`任务已加入队列${result.task_id?`：${result.task_id}`:""}`)}
    catch(error){setMessage(error instanceof Error?error.message:"任务创建失败")}
    finally{setLoading(false)}
  };
  const cscecSources=sources.filter(source=>source.entity_id||source.source_name.includes("中国建筑")||source.source_name.includes("中建"));
  return <><div className="page-title"><div><small className="eyebrow">CSCEC KEY ACCOUNT MONITOR</small><h1>中国建筑 KA 组织与领导动态</h1><p>组织主数据、官网动态、上市公告、领导任免与销售相关合作统一追溯。境内合作全部保留，海外项目优先展示并标记国家/地区。</p></div><div className="title-actions">{user.role==="admin"&&<><button className="btn" disabled={loading} onClick={()=>void adminAction("/api/admin/cscec/entities/sync")}>同步组织架构</button><button className="btn primary" disabled={loading} onClick={()=>void adminAction("/api/admin/crawl/cscec/all",{})}>抓取中建来源</button><button className="btn" disabled={loading} onClick={()=>void adminAction("/api/admin/crawl/cscec/backfill",{})}>回填最近365天</button></>}</div></div>
  {message&&<div className="toast">{message}<button onClick={()=>setMessage("")}>×</button></div>}
  <div className="source-metrics"><Metric label="组织实体" value={entities.length}/><Metric label="销售相关资讯" value={events.length}/><Metric label="领导动态" value={leadership.length}/><Metric label="组织变化" value={organization.length}/></div>
  <div className="filterbar"><select value={entityId} onChange={event=>setEntityId(event.target.value)}><option value="">全部中建实体</option>{entities.map(entity=><option key={entity.entity_id} value={entity.entity_id}>{entity.canonical_name}</option>)}</select><button className="btn" onClick={()=>void load()} disabled={loading}>{loading?"加载中…":"刷新"}</button></div>
  <div className="segmented cscec-tabs">{([["events","资讯时间线"],["leadership","领导动态"],["organization","组织变化"],["entities","组织主数据"]] as const).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==="events"&&<section className="list-panel"><div className="list-head"><b>中建公开资讯</b><span>海外项目优先；境内合作保留并标记国家/地区</span></div><ArticleList items={events} onOpen={onOpen} empty="尚无符合条件的中建公开资讯"/></section>}
  {tab==="leadership"&&<section className="cscec-card-grid">{leadership.map(item=><a className="cscec-event-card" href={item.source_url} target="_blank" rel="noreferrer" key={item.id}><div><Badge tone={item.verification_status==="source_verified"?"good":"warn"}>{item.verification_status}</Badge><Badge>{CSCEC_EVENT_LABELS[item.appointment_type]||item.appointment_type}</Badge><Badge>{item.country||item.region||"地区待核验"}</Badge></div><h3>{item.person_name||"姓名待核验"} · {item.counterparty?`与${item.counterparty}动态`:item.title_after||item.title_before||"职务动态"}</h3><p>{item.evidence_excerpt}</p><small>{fmt(item.published_at)} · {item.source_name} · {Math.round(item.confidence*100)}% 置信度</small></a>)}</section>}
  {tab==="organization"&&<section className="cscec-card-grid">{organization.map(item=><article className="cscec-event-card" key={item.id}><div><Badge tone={item.verification_status==="source_verified"?"good":"warn"}>{item.verification_status}</Badge><Badge>{item.change_type}</Badge></div><h3>{item.display_title}</h3><p>{item.evidence_excerpt}</p><small>{fmt(item.published_at)} · {item.source_count} 个来源</small>{item.source_urls.map(url=><a href={url} target="_blank" rel="noreferrer" key={url}>打开原始来源 →</a>)}</article>)}</section>}
  {tab==="entities"&&<div className="source-table-wrap"><table><thead><tr><th>机构</th><th>层级 / 类型</th><th>上级 entity_id</th><th>地区</th><th>核验状态</th><th>官方入口</th></tr></thead><tbody>{entities.map(entity=><tr key={entity.entity_id}><td><b>{entity.canonical_name}</b><small>{entity.short_name||entity.entity_id}</small></td><td>{entity.entity_level}<small>{entity.entity_type}</small></td><td><code>{entity.parent_entity_id||"—"}</code></td><td>{entity.overseas?"海外":"境内"}<small>{entity.country||entity.region||"待核验"}</small></td><td><Badge tone={entity.verification_status==="verified"?"good":"warn"}>{entity.verification_status}</Badge></td><td>{entity.official_url?<a href={entity.official_url} target="_blank" rel="noreferrer">打开官网 →</a>:<span>未发现独立官网</span>}</td></tr>)}</tbody></table></div>}
  <section className="panel cscec-source-health"><div className="panel-head"><div><h2>中建来源健康度</h2><p>待适配和受限来源不会被伪装为可运行。</p></div></div><div className="focus-grid"><Metric label="配置来源" value={cscecSources.length}/><Metric label="可自动运行" value={cscecSources.filter(x=>x.adapter_status==="active"&&x.enabled).length}/><Metric label="仅人工导入" value={cscecSources.filter(x=>x.adapter_status==="manual_only").length}/></div></section></>;
}

function SourcesPage({sources,user,reload,onImport,onBatch}:{sources:Source[];user:SessionUser;reload:()=>void;onImport:()=>void;onBatch:()=>void}){
  const active=sources.filter(x=>x.enabled&&x.adapter_status==="active").length;const pending=sources.filter(x=>x.adapter_status==="pending_adapter").length;const failed=sources.filter(x=>x.latest_status==="failed"||x.adapter_status==="paused").length;
  return <><div className="page-title"><div><small className="eyebrow">SOURCE GOVERNANCE</small><h1>数据源管理</h1><p>列表仅展示状态；单来源调试不再占用每一行操作位。</p></div><div className="title-actions">{ROLE_LEVEL[user.role]>=2&&<button className="btn" onClick={onImport}>＋ 手动导入</button>}{user.role==="admin"&&<button className="btn primary" onClick={onBatch}>一键抓取全部可运行来源</button>}</div></div><div className="source-metrics"><Metric label="来源总数" value={sources.length}/><Metric label="可自动运行" value={active}/><Metric label="待适配" value={pending}/><Metric label="失败或暂停" value={failed}/></div><div className="source-table-wrap"><table><thead><tr><th>来源</th><th>类型 / 可信度</th><th>适配状态</th><th>最近运行</th><th>历史回填</th><th>本次抓取结果</th><th>启用</th></tr></thead><tbody>{sources.map(s=><tr key={s.id}><td><b>{s.source_name}</b><a href={s.source_url} target="_blank" rel="noreferrer">打开原站 →</a></td><td><span>{s.source_type}</span><Badge tone={s.reliability_level==="high"?"good":s.reliability_level==="low"?"bad":"warn"}>{s.reliability_level}</Badge></td><td><span className={`status ${s.adapter_status}`}>{s.adapter_status}</span><small>{s.crawl_method}</small></td><td><span>{s.latest_status}</span><small>{fmt(s.last_success_at)}</small></td><td><span>{s.backfill_status}</span><small>{s.backfill_cursor?`断点 ${s.backfill_cursor}`:fmt(s.last_backfill_at)}</small></td><td><span title={s.latest_failure_reason||""}>{s.latest_failure_reason||`读取 ${s.latest_fetched_count} · 新增 ${s.latest_new_count} · 更新 ${s.latest_updated_count} · 去重 ${s.latest_duplicate_count} · 过滤 ${s.latest_skipped_count}`}</span></td><td><button className={`switch ${s.enabled?"on":""}`} disabled={user.role!=="admin"||!["active","manual_only","paused"].includes(s.adapter_status)} aria-label={`${s.enabled?"禁用":"启用"} ${s.source_name}`} onClick={async()=>{await api(`/api/sources/${s.id}`,{method:"PATCH",body:JSON.stringify({enabled:!s.enabled})});reload()}}><i/></button></td></tr>)}</tbody></table></div></>;
}

function BatchesPage({batches,user,reload,openBatch}:{batches:Batch[];user:SessionUser;reload:()=>void;openBatch:(b:Batch)=>void}){
  if(user.role!=="admin")return <div className="empty-state"><b>仅管理员可查看抓取批次</b></div>;
  return <><div className="page-title"><div><small className="eyebrow">CELERY BATCH OPERATIONS</small><h1>抓取批次</h1><p>浏览器只创建批次；所有来源由Worker按队列、限速和重试策略执行。</p></div><button className="btn" onClick={reload}>刷新进度</button></div><section className="batch-grid">{batches.map(b=><button key={b.id} onClick={()=>openBatch(b)}><div><Badge tone={b.status.includes("error")?"bad":b.status.includes("complete")?"good":"warn"}>{b.status}</Badge><small>{fmt(b.created_at)}</small></div><b>{b.id.slice(0,8)}</b><progress value={b.completed} max={Math.max(1,b.total_sources)}/><span>{b.completed}/{b.total_sources} 完成 · 成功 {b.success} · 空结果 {b.empty} · 失败 {b.failed} · 跳过 {b.skipped}</span><em>新增 {b.new_count} · 更新 {b.updated_count} · 去重 {b.duplicate_count}</em></button>)}</section>{!batches.length&&<div className="empty-state"><b>尚未创建全量抓取批次</b></div>}</>;
}

function BackfillsPage({runs,sources,user,reload}:{runs:Backfill[];sources:Source[];user:SessionUser;reload:()=>void}){
  const [sourceId,setSourceId]=useState("");const [busy,setBusy]=useState(false);const runnable=sources.filter(x=>x.adapter_status==="active"&&x.enabled);
  const create=async()=>{if(!sourceId)return;setBusy(true);try{await api("/api/admin/backfills",{method:"POST",body:JSON.stringify({source_id:sourceId,date_from:new Date(`${oneYearAgo()}T00:00:00Z`).toISOString(),date_to:new Date().toISOString(),page_limit:sources.find(x=>x.id===sourceId)?.backfill_page_limit||25})});reload()}finally{setBusy(false)}};
  const control=async(id:string,action:"pause"|"resume"|"retry"|"cancel")=>{setBusy(true);try{await api(`/api/admin/backfills/${id}/${action}`,{method:"POST"});reload()}finally{setBusy(false)}};
  if(user.role!=="admin")return <div className="empty-state"><b>仅管理员可管理历史回填</b></div>;
  return <><div className="page-title"><div><small className="eyebrow">ONE-YEAR BACKFILL</small><h1>历史回填管理</h1><p>回填分页、断点和未核验日期均真实记录；不会把缺失发布日期的数据算入最近一年。</p></div></div><div className="filterbar"><select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">选择可运行来源</option>{runnable.map(x=><option value={x.id} key={x.id}>{x.source_name}</option>)}</select><button className="btn primary" onClick={create} disabled={!sourceId||busy}>{busy?"正在处理…":"回填最近一年"}</button><button className="btn" onClick={reload}>刷新状态</button></div><section className="list-panel"><div className="list-head"><b>回填任务</b><span>{runs.length} 个</span></div>{runs.map(r=><div className="backfill-row" key={r.id}><div><b>{r.source_name}</b><small>{fmt(r.created_at)} · {r.status}</small></div><progress value={r.current_page} max={Math.max(1,r.page_limit)}/><span>页 {r.current_page}/{r.page_limit}</span><span>读取 {r.fetched_count} · 新增 {r.new_count} · 去重 {r.duplicate_count}</span><Badge tone={r.date_unverified_count?"warn":"good"}>日期待核验 {r.date_unverified_count}</Badge>{r.failure_reason&&<em>{r.failure_reason}</em>}<div className="backfill-actions">{r.status==="running"&&<button className="btn" disabled={busy} onClick={()=>void control(r.id,"pause")}>暂停</button>}{r.status==="paused"&&<button className="btn primary" disabled={busy} onClick={()=>void control(r.id,"resume")}>继续</button>}{r.status==="failed"&&<button className="btn primary" disabled={busy} onClick={()=>void control(r.id,"retry")}>重试</button>}{["queued","running","paused"].includes(r.status)&&<button className="btn danger" disabled={busy} onClick={()=>void control(r.id,"cancel")}>取消</button>}</div></div>)}</section></>;
}

function BatchConfirm({onClose,onCreated}:{onClose:()=>void;onCreated:(b:Batch)=>void}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const run=async()=>{setBusy(true);setError("");try{onCreated(await api<Batch>("/api/admin/crawl-batches",{method:"POST",body:JSON.stringify({})}))}catch(e){setError(e instanceof Error?e.message:"创建失败")}finally{setBusy(false)}};
  return <div className="overlay"><div className="modal confirm-modal"><div className="modal-head"><div><small className="eyebrow">ADMIN CONFIRMATION</small><h2>启动全量可运行来源抓取？</h2><p>系统只会将启用且适配状态为 active 的来源加入Celery队列，并自动跳过公众号、受限、禁用、暂停和待适配来源。</p></div><button className="icon-btn" onClick={onClose}>×</button></div><div className="compliance"><b>合规与幂等保护</b>同一时间只允许一个全量批次；域名限速、并发限制和失败重试继续生效。</div>{error&&<div className="login-error">{error}</div>}<div className="modal-actions"><button className="btn" onClick={onClose}>取消</button><button className="btn primary" onClick={run} disabled={busy}>{busy?"正在创建批次…":"确认并加入队列"}</button></div></div></div>;
}

function BatchDrawer({batch,onClose,onChange}:{batch:Batch;onClose:()=>void;onChange:(b:Batch)=>void}){
  const [data,setData]=useState(batch);useEffect(()=>{let active=true;const update=async()=>{try{const next=await api<Batch>(`/api/admin/crawl-batches/${batch.id}`);if(active){setData(next);onChange(next)}}catch{}};void update();const timer=setInterval(()=>{if(!["completed","completed_with_errors","cancelled"].includes(data.status))void update()},5000);return()=>{active=false;clearInterval(timer)}},[batch.id,data.status,onChange]);
  return <div className="overlay"><aside className="drawer batch-drawer"><div className="drawer-head"><div><small className="eyebrow">CRAWL BATCH</small><h2>批次 {data.id.slice(0,8)}</h2><p>{data.status} · {data.completed}/{data.total_sources} 完成</p></div><button className="icon-btn" onClick={onClose}>×</button></div><section><progress value={data.completed} max={Math.max(1,data.total_sources)}/><div className="focus-grid"><Metric label="成功" value={data.success}/><Metric label="空结果" value={data.empty}/><Metric label="失败" value={data.failed}/><Metric label="跳过" value={data.skipped}/><Metric label="新增" value={data.new_count}/><Metric label="去重" value={data.duplicate_count}/></div></section>{data.current_sources.length>0&&<section><h4>当前运行来源</h4><p>{data.current_sources.join("、")}</p></section>}<section><h4>来源明细</h4>{data.items?.map(x=><div className="batch-item" key={x.id}><b>{x.source_name}</b><Badge tone={x.status==="failed"?"bad":x.status==="success"?"good":"neutral"}>{x.status}</Badge><small>{x.failure_reason||x.skip_reason||""}</small></div>)}</section>{["queued","running"].includes(data.status)&&<section><button className="btn danger" onClick={async()=>setData(await api<Batch>(`/api/admin/crawl-batches/${data.id}/cancel`,{method:"POST"}))}>取消尚未执行的任务</button></section>}</aside></div>;
}

function Detail({article,user,onClose,onChange,showReview=true}:{article:Article;user:SessionUser;onClose:()=>void;onChange:()=>void;showReview?:boolean}){
  return <div className="overlay"><aside className="drawer"><div className="drawer-head"><div><small className="eyebrow">TRACEABLE EVIDENCE</small><h2>{article.original_title||article.title}</h2><p>{article.source_name} · {fmt(article.published_at)}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><div className="drawer-badges"><Badge tone={article.reliability_level==="high"?"good":"warn"}>{article.reliability_level} 可信度</Badge><Badge>{article.date_verification_status}</Badge><Badge>{article.verification_status}</Badge>{article.canonical_event&&<Badge>{article.canonical_event.source_count} 个事件来源</Badge>}</div>{article.verification_notice&&<div className="verification-alert"><b>媒体线索，建议核验官方公告</b><span>销售建议不得把未核验媒体报道当作最终事实。</span></div>}<section><h4>事实摘要</h4><p className="lead">{article.summary}</p></section><section className="insight-box"><h4>销售洞察 <small>来源等级：{article.reliability_level}</small></h4><p>{article.sales_insight}</p></section><section><h4>结构化识别</h4><div className="detail-grid"><div><label>国家 / 区域</label><p>{article.country||"待核验"} / {article.region||"待核验"}</p></div><div><label>情报类型</label><p>{article.intelligence_types.map(x=>TYPE_LABELS[x]||x).join("、")||"待分类"}</p></div><div><label>KA候选</label><p>{article.ka_candidates.map(x=>`${x.ka_group} ${Math.round(x.confidence*100)}%${x.needs_review?"（待审）":""}`).join("、")||"无"}</p></div><div><label>项目阶段</label><p>{article.project_stage||"待识别"}</p></div></div></section><section><h4>来源证据</h4><div className="source-card"><div><b>{article.source_name}</b><span>{article.source_type} · {article.reliability_level}</span></div><a href={article.original_url} target="_blank" rel="noreferrer">打开原始链接 ↗</a></div>{article.supporting_sources?.map((s,i)=><div className="supporting-source" key={`${s.source_id}-${i}`}><div><b>{s.source_role} · {s.reliability_level}</b><span>{s.title}</span><small>{fmt(s.published_at)} · {s.consistency_status}</small></div><a href={s.original_url} target="_blank" rel="noreferrer">原文 ↗</a></div>)}</section>{showReview&&ROLE_LEVEL[user.role]>=2&&<section><h4>人工审核</h4><div className="modal-actions"><button className="btn" onClick={async()=>{await api(`/api/articles/${article.id}/review`,{method:"POST",body:JSON.stringify({action:"needs_changes",notes:"需补充官方来源"})});onChange()}}>需要补证</button><button className="btn primary" onClick={async()=>{await api(`/api/articles/${article.id}/review`,{method:"POST",body:JSON.stringify({action:"approve",notes:"已核验"})});onChange()}}>审核通过</button></div></section>}</aside></div>;
}

function ImportModal({sources,onClose,onDone}:{sources:Source[];onClose:()=>void;onDone:()=>void}){
  const manual=sources.filter(s=>s.adapter_status==="manual_only");const [kind,setKind]=useState<"wechat"|"web">("wechat");const [error,setError]=useState("");const [extracting,setExtracting]=useState(false);const [url,setUrl]=useState("");const [title,setTitle]=useState("");const [content,setContent]=useState("");const [published,setPublished]=useState("");const [webSource,setWebSource]=useState("用户手动导入网页");
  const extract=async()=>{if(!url){setError("请先填写公开文章链接");return}setExtracting(true);setError("");try{const preview=await api<{title:string;content_text:string;published_at:string|null}>("/api/articles/manual-import/preview",{method:"POST",body:JSON.stringify({original_url:url,import_type:kind})});setTitle(preview.title);setContent(preview.content_text);if(preview.published_at)setPublished(preview.published_at.slice(0,16))}catch(err){setError(`${err instanceof Error?err.message:"提取失败"}；你仍可手动粘贴标题和正文。`)}finally{setExtracting(false)}};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);try{await api("/api/articles/manual-import",{method:"POST",body:JSON.stringify({original_url:url,title,content_text:content,published_at:published||null,source_name:kind==="wechat"?form.get("source"):webSource,import_type:kind})});onDone()}catch(err){setError(err instanceof Error?err.message:"导入失败")}};
  return <div className="overlay"><form className="modal" onSubmit={submit}><div className="modal-head"><div><h2>手动导入公开文章</h2><p>公众号不会进入定时抓取；只有你点击“从链接提取”时才读取公开页面。</p></div><button className="icon-btn" type="button" onClick={onClose}>×</button></div><div className="segmented"><button type="button" className={kind==="wechat"?"active":""} onClick={()=>setKind("wechat")}>公众号</button><button type="button" className={kind==="web"?"active":""} onClick={()=>setKind("web")}>公开网页</button></div>{error&&<div className="login-error">{error}</div>}<div className="form-grid">{kind==="wechat"?<label>来源<select name="source" required>{manual.map(s=><option key={s.id}>{s.source_name}</option>)}</select></label>:<label>来源名称<input value={webSource} onChange={e=>setWebSource(e.target.value)} required/></label>}<label>发布时间<input value={published} onChange={e=>setPublished(e.target.value)} type="datetime-local"/></label><label className="wide">原始链接<div className="url-extract-row"><input value={url} onChange={e=>setUrl(e.target.value)} type="url" required/><button className="btn" type="button" onClick={extract} disabled={extracting}>{extracting?"正在提取…":"从链接提取"}</button></div></label><label className="wide">原始标题<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label className="wide">正文<textarea value={content} onChange={e=>setContent(e.target.value)} rows={9} minLength={20} required/></label></div><div className="compliance"><b>合规说明</b>不绕过登录、验证码、robots.txt 或付费墙；公众号与媒体内容始终按线索处理，关键事实建议核验官方来源。</div><div className="modal-actions"><button className="btn" type="button" onClick={onClose}>取消</button><button className="btn primary">导入并标记为线索</button></div></form></div>;
}

export default function Page(){
  const initialView=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("view")||"dashboard":"dashboard";
  const normalizedView=initialView==="country"||initialView==="region"?"opportunities":initialView;
  const [view,setView]=useState(normalizedView);const [countryFilter,setCountryFilter]=useState(typeof window!=="undefined"?new URLSearchParams(window.location.search).get("country")||"":"");
  const [user,setUser]=useState<SessionUser|null>(null);const [authLoading,setAuthLoading]=useState(false);const [authNotice,setAuthNotice]=useState("");const [articles,setArticles]=useState<Article[]>([]);const [sources,setSources]=useState<Source[]>([]);const [status,setStatus]=useState<Status|null>(null);const [stats,setStats]=useState<Stats|null>(null);const [groups,setGroups]=useState<KAGroup[]>([]);const [batches,setBatches]=useState<Batch[]>([]);const [backfills,setBackfills]=useState<Backfill[]>([]);const [loading,setLoading]=useState(false);const [detail,setDetail]=useState<Article|null>(null);const [importing,setImporting]=useState(false);const [confirmBatch,setConfirmBatch]=useState(false);const [batchDetail,setBatchDetail]=useState<Batch|null>(null);const [error,setError]=useState("");
  const load=useCallback(async(q="",reliability="",type="")=>{if(!user)return;setLoading(true);setError("");try{const params=new URLSearchParams({page_size:"200"});if(q)params.set("q",q);if(reliability)params.set("reliability",reliability);if(type)params.set("intelligence_type",type);const base=[api<{items:Article[]}>(`/api/articles?${params}`),api<Source[]>("/api/sources"),api<Status>("/api/dashboard/status"),api<Stats>("/api/stats"),api<KAGroup[]>("/api/ka-groups")] as const;const [feed,sourceList,health,statistics,kaList]=await Promise.all(base);setArticles(feed.items);setSources(sourceList);setStatus(health);setStats(statistics);setGroups(kaList);if(user.role==="admin"){const [batchList,backfillList]=await Promise.all([api<Batch[]>("/api/admin/crawl-batches"),api<Backfill[]>("/api/admin/backfills")]);setBatches(batchList);setBackfills(backfillList)}}catch(e){setError(e instanceof Error?e.message:"数据加载失败")}finally{setLoading(false)}},[user]);
  useEffect(()=>{const expired=()=>{setUser(null);setError("");setDetail(null);setImporting(false)};window.addEventListener(AUTH_EXPIRED_EVENT,expired);return()=>window.removeEventListener(AUTH_EXPIRED_EVENT,expired)},[]);
  useEffect(()=>{if(!hasSession())return;let active=true;const timer=window.setTimeout(()=>{if(!active)return;setAuthLoading(true);void(async()=>{try{const current=await api<SessionUser>("/api/auth/me");if(active)setUser(current)}catch(e){clearSession();if(active)setAuthNotice(e instanceof Error?e.message:"会话检查失败，请重新登录")}finally{if(active)setAuthLoading(false)}})()},0);return()=>{active=false;window.clearTimeout(timer)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const navigate=(next:string,country="")=>{setView(next);setCountryFilter(country);const params=new URLSearchParams();params.set("view",next);if(country)params.set("country",country);window.history.replaceState({},``,`${window.location.pathname}?${params}`);window.scrollTo({top:0,behavior:"smooth"})};
  const open=async(a:Article)=>{try{setDetail(await api<Article>(`/api/articles/${a.id}`))}catch{setDetail(a)}if(!a.read&&user&&ROLE_LEVEL[user.role]>=1){try{await api(`/api/articles/${a.id}/read`,{method:"PUT"});setArticles(xs=>xs.map(x=>x.id===a.id?{...x,read:true}:x))}catch{}}};
  const specialized=useMemo(()=>({market:articles.filter(a=>a.intelligence_types.some(x=>["market_project","new_factory","data_center","rail_transit","power_grid","renewable_energy","energy_storage","industrial_park","manufacturing","building_infrastructure","oil_gas_chemical","mining_metals"].includes(x))),policies:articles.filter(a=>a.intelligence_types.some(x=>x.includes("policy")||["foreign_access","trade_tariff","standards_compliance"].includes(x))),competitors:articles.filter(a=>a.intelligence_types.includes("competitor")||a.source_type==="competitor"),chambers:articles.filter(a=>a.intelligence_types.includes("chamber_association")||a.source_type==="chamber"),review:articles.filter(a=>a.review_status!=="approved")}),[articles]);
  const content=(()=>{if(view==="dashboard")return <Dashboard stats={stats} status={status} onCountry={c=>navigate("opportunities",c)} navigate={navigate}/>;if(view==="intelligence")return <FeedPage title="全部情报" subtitle="默认展示最近365天、有真实发布日期且可追溯的生产数据。" items={articles} loading={loading} onOpen={open} onSearch={load}/>;if(view==="market")return <FeedPage title="市场与行业机会" subtitle="工厂、数据中心、轨交、电网、能源与基础设施项目。" items={specialized.market} loading={loading} onOpen={open} onSearch={load}/>;if(view==="opportunities")return <Opportunities stats={stats} articles={articles} initialCountry={countryFilter} onCountry={c=>navigate("opportunities",c)} onOpen={open}/>;if(view==="policies")return <PolicyPage onOpen={open}/>;if(view==="ka")return <KAPage groups={groups} onOpen={open}/>;if(view==="cscec")return <CSCECPage user={user!} onOpen={open} sources={sources}/>;if(view==="competitors")return <FeedPage title="竞争对手动态" subtitle="仅展示官网、公告和专业媒体中的可追溯动态。" kind="competitor" items={specialized.competitors} loading={loading} onOpen={open} onSearch={load}/>;if(view==="chambers")return <FeedPage title="商协会动态" subtitle="商会、协会和官方行业机构公开信息。" kind="chamber_association" items={specialized.chambers} loading={loading} onOpen={open} onSearch={load}/>;if(view==="sources")return <SourcesPage sources={sources} user={user!} reload={()=>void load()} onImport={()=>setImporting(true)} onBatch={()=>setConfirmBatch(true)}/>;if(view==="batches")return <BatchesPage batches={batches} user={user!} reload={()=>void load()} openBatch={b=>setBatchDetail(b)}/>;if(view==="backfills")return <BackfillsPage runs={backfills} sources={sources} user={user!} reload={()=>void load()}/>;return <FeedPage title="人工审核" subtitle="弱关键词、低置信度、多KA候选和媒体线索进入人工审核。" items={specialized.review} loading={loading} onOpen={open} onSearch={load}/>})();
  if(!user)return <Login checking={authLoading} notice={authNotice} onSuccess={u=>{setAuthNotice("");setUser(u)}}/>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">SE</span><div><b>海外销售情报</b><small>Schneider Electric</small></div></div><nav>{NAV.filter(([id])=>user.role==="admin"||!["batches","backfills"].includes(id)).map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>navigate(id)}><span>•</span>{label}{id==="sources"&&<i>{sources.length}</i>}</button>)}</nav><div className="sidebar-foot"><div className="coverage"><span>一年期生产数据</span><b>{stats?.year_intelligence_count??0} 个去重事件</b><i><em style={{width:status?.delay_status==="healthy"?"100%":"35%"}}/></i><small>{status?.last_successful_update?`更新于 ${fmt(status.last_successful_update)}`:"等待首次成功抓取"}</small></div><button className="user" onClick={async()=>{await logout();setUser(null)}}><span>{user.full_name.slice(0,2)}</span><div><b>{user.full_name}</b><small>{user.role} · 退出登录</small></div></button></div></aside><div className="workspace"><header className="topbar"><div><b>销售情报工作台</b><small className="api-indicator"><i className={error?"bad":""}/>{error||"API 已连接"}</small></div><div className="top-actions"><button className="sync" onClick={()=>void load()} disabled={loading}>{loading?"更新中…":status?.is_updating?`抓取运行中 ${status.running_count}`:"刷新数据"}</button></div></header><main>{content}</main></div>{detail&&<Detail article={detail} user={user} onClose={()=>setDetail(null)} onChange={async()=>{await load();setDetail(null)}} showReview={view!=="cscec"}/>} {importing&&<ImportModal sources={sources} onClose={()=>setImporting(false)} onDone={()=>{setImporting(false);void load()}}/>}{confirmBatch&&<BatchConfirm onClose={()=>setConfirmBatch(false)} onCreated={b=>{setConfirmBatch(false);setBatches(xs=>[b,...xs]);setBatchDetail(b)}}/>}{batchDetail&&<BatchDrawer batch={batchDetail} onClose={()=>setBatchDetail(null)} onChange={next=>setBatches(xs=>xs.map(x=>x.id===next.id?next:x))}/>}</div>;
}
