"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { API_BASE, api, clearSession, hasSession, login, logout, type SessionUser } from "./api-client";

type Article = {
  id: string; title: string; original_title: string; summary: string; sales_insight: string; original_url: string;
  source_name: string; source_type: string; reliability_level: "high" | "medium" | "low"; published_at: string | null;
  fetched_at: string; country: string | null; region: string | null; ka: string[]; subsidiary: string[]; industries: string[];
  project_type: string | null; project_stage: string | null; project_value: number | null; currency: string | null;
  overseas_evidence: string[]; ka_match_evidence: string[]; confidence_score: number; verification_status: string;
  cross_source_count: number; is_primary_source: boolean; review_status: string; favorite: boolean; read: boolean;
  verification_notice: string | null; ai_payload: { next_action?: string; recommended_sales_action?: string; product_opportunities?: string[] };
  supporting_sources?: { source_id:string; title:string; original_url:string; published_at:string|null; reliability_level:string; is_primary:boolean }[];
};
type Source = {
  id: string; source_name: string; source_url: string; source_type: string; reliability_level: "high" | "medium" | "low";
  region_focus: string[]; country_focus: string[]; industry_focus: string[]; source_tags: string[]; crawl_method: string; adapter_status: string;
  schedule_minutes: number | null; enabled: boolean; notes: string; last_success_at: string | null; last_failure_at: string | null;
  next_run_at: string | null; latest_new_count: number; latest_status: string; latest_failure_reason: string | null; consecutive_failures: number;
};
type Status = { last_successful_update: string | null; is_updating: boolean; running_count: number; last_new_count: number; failed_source_count: number; data_delay_minutes: number | null; delay_status: string };
type Stats = { counting_basis: string; countries: { name: string; value: number }[]; regions: { name: string; value: number }[] };

const TYPE_LABEL: Record<string, string> = { official:"官方", media:"媒体", procurement:"招采", chamber:"商会/协会", report:"报告", wechat_manual:"公众号手动", stock_disclosure:"上市公告", competitor:"竞争对手", policy:"政策" };
const STATUS_LABEL: Record<string, string> = { active:"可运行", pending_adapter:"待适配", manual_only:"仅手动", blocked:"受限", disabled:"已停用", paused:"故障暂停" };
const ROLE_LEVEL = { viewer:1, sales:2, analyst:3, admin:4 };
const NAV = [["dashboard","总览"],["intelligence","资讯情报"],["country","国家机会"],["region","区域机会"],["sources","数据源管理"]] as const;

function fmt(value: string | null) { if (!value) return "暂无"; return new Intl.DateTimeFormat("zh-CN", { dateStyle:"medium", timeStyle:"short" }).format(new Date(value)); }
function reliabilityText(level: string) { return level === "high" ? "高可信" : level === "medium" ? "中可信" : "低可信"; }

function Login({ onSuccess }: { onSuccess: (user: SessionUser) => void }) {
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form=new FormData(event.currentTarget); try { onSuccess(await login(String(form.get("email")),String(form.get("password")))); } catch (e) { setError(e instanceof Error ? e.message : "登录失败"); } finally { setBusy(false); } }
  return <main className="login-page"><section className="login-brand"><div className="brand-mark big">SE</div><p>SCHNEIDER ELECTRIC</p><h1>海外销售情报工作台</h1><span>可信来源 · 持续采集 · 可追溯销售线索</span></section><form className="login-card" onSubmit={submit}><div className="eyebrow">SECURE WORKSPACE</div><h2>登录工作台</h2><p>使用管理员创建的团队账号继续。</p>{!API_BASE && <div className="login-error">部署尚未配置 API 地址。</div>}{error && <div className="login-error">{error}</div>}<label>工作邮箱<input name="email" type="email" autoComplete="username" required /></label><label>密码<input name="password" type="password" autoComplete="current-password" required /></label><button className="btn primary login-submit" disabled={busy || !API_BASE}>{busy ? "正在验证…" : "登录"}</button><small>连续 5 次登录失败将锁定账号 15 分钟。</small></form></main>;
}

function Empty({ title, detail }: { title:string; detail:string }) { return <div className="empty-state"><b>{title}</b><p>{detail}</p></div>; }
function Level({ level }: { level:string }) { return <span className={`badge ${level}`}>{reliabilityText(level)}</span>; }
function Metric({ label,value,detail }: {label:string;value:string|number;detail:string}) { return <div className="metric-card"><div className="metric-top"><span>{label}</span></div><strong>{value}</strong><small>{detail}</small></div>; }

function ArticleRow({ article, onOpen }: { article: Article; onOpen:(article:Article)=>void }) {
  return <button className={`article-row ${article.read ? "is-read" : ""}`} onClick={()=>onOpen(article)}><div className="article-main"><div className="article-badges"><Level level={article.reliability_level}/><span className="badge category">{TYPE_LABEL[article.source_type] || article.source_type}</span>{article.cross_source_count > 1 && <span className="badge verified">{article.cross_source_count} 源验证</span>}</div><h3>{article.title}</h3><p>{article.summary || "尚未生成摘要"}</p><div className="article-meta"><span>{article.country || "国家待识别"}</span><span>{article.region || "区域待识别"}</span><span>{article.source_name}</span><span>{fmt(article.published_at)}</span></div></div><div className="score"><b>{Math.round(article.confidence_score*100)}</b><span>置信度</span><em>›</em></div></button>;
}

function Bars({ data, onSelect }: { data:{name:string;value:number}[]; onSelect?:(name:string)=>void }) {
  const max=Math.max(1,...data.map(x=>x.value));
  return <div className="bars">{data.map(x=><button className="bar-col" key={x.name} onClick={()=>onSelect?.(x.name)}><span className="bar-num">{x.value}</span><i className="bar" style={{height:`${Math.max(6,x.value/max*100)}%`}}/><span className="bar-label">{x.name}</span></button>)}</div>;
}

function Dashboard({ articles,status,stats,navigate,onOpen }: {articles:Article[];status:Status|null;stats:Stats|null;navigate:(v:string,f?:string)=>void;onOpen:(a:Article)=>void}) {
  const high=articles.filter(x=>x.reliability_level === "high").length; const verified=articles.filter(x=>x.cross_source_count>1).length;
  return <><div className="page-title"><div><div className="eyebrow">GLOBAL SALES INTELLIGENCE</div><h1>海外销售情报总览</h1><p>中资 EPC 海外项目 · 官方优先 · 每条线索可追溯</p></div><div className="fresh"><span className={status?.is_updating ? "pulse active" : "pulse"}/>{status?.is_updating ? `${status.running_count} 个来源抓取中` : `最近更新 ${fmt(status?.last_successful_update || null)}`}</div></div><div className="metrics"><Metric label="有效情报" value={articles.length} detail="生产库中的非演示记录"/><Metric label="高可信来源" value={high} detail="官方、业主、招投标或公告"/><Metric label="多源交叉验证" value={verified} detail="同一事件至少两个独立来源"/><Metric label="异常来源" value={status?.failed_source_count ?? "—"} detail={status?.data_delay_minutes == null ? "尚无成功抓取记录" : `数据延迟 ${status.data_delay_minutes} 分钟`}/></div><div className="dashboard-grid"><section className="panel focus-panel"><div className="panel-head"><div><span className="section-kicker">LATEST SIGNALS</span><h2>最新重点资讯</h2></div><button onClick={()=>navigate("intelligence")}>查看全部 →</button></div>{articles.length ? articles.slice(0,6).map(x=><ArticleRow key={x.id} article={x} onOpen={onOpen}/>) : <Empty title="尚无生产情报" detail="Worker 首次成功采集并通过海外识别后，资讯会出现在这里。"/>}</section><section className="panel chart-panel"><div className="panel-head"><div><span className="section-kicker">COUNTRY RANKING</span><h2>国家项目热度</h2></div></div>{stats?.countries.length ? <Bars data={stats.countries} onSelect={x=>navigate("country",x)}/> : <Empty title="暂无国家统计" detail="统计口径只包含去重后的生产数据。"/>}</section></div></>;
}

function Feed({ articles,loading,onOpen,onSearch }: {articles:Article[];loading:boolean;onOpen:(a:Article)=>void;onSearch:(q:string,reliability:string)=>void}) {
  const [query,setQuery]=useState(""); const [level,setLevel]=useState("");
  return <><div className="page-title"><div><div className="eyebrow">INTELLIGENCE FEED</div><h1>海外资讯情报</h1><p>媒体与公众号仅作为线索；缺少官方支撑时会明确提示核验。</p></div></div><form className="filterbar" onSubmit={e=>{e.preventDefault();onSearch(query,level)}}><label className="search-field"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索项目、KA、国家或关键词"/></label><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">可信度：全部</option><option value="high">高可信</option><option value="medium">中可信</option><option value="low">低可信</option></select><button className="btn primary">检索</button></form><div className="list-panel"><div className="list-head"><b>{loading ? "正在加载…" : `${articles.length} 条结果`}</b><span>PostgreSQL 全文检索</span></div>{articles.length ? articles.map(x=><ArticleRow key={x.id} article={x} onOpen={onOpen}/>) : !loading && <Empty title="没有匹配结果" detail="调整筛选条件，或等待采集任务产生新数据。"/>}</div></>;
}

function Opportunity({ kind,data,articles,initial,onOpen }: {kind:"country"|"region";data:{name:string;value:number}[];articles:Article[];initial:string;onOpen:(a:Article)=>void}) {
  const [selected,setSelected]=useState(initial || data[0]?.name || "");
  const items=articles.filter(x=>(kind === "country" ? x.country : x.region) === selected);
  return <><div className="page-title"><div><div className="eyebrow">{kind === "country" ? "COUNTRY OPPORTUNITY" : "REGIONAL RADAR"}</div><h1>{kind === "country" ? "国家机会" : "区域机会"}</h1><p>统计来自去重后的生产情报，不包含静态样例。</p></div></div>{data.length ? <div className="opportunity-layout"><aside className="rank-menu">{data.map((x,i)=><button className={selected===x.name?"active":""} key={x.name} onClick={()=>setSelected(x.name)}><span>{String(i+1).padStart(2,"0")}</span><b>{x.name}</b><em>{x.value} 条</em></button>)}</aside><main><div className="hero-stat"><div><span>当前聚焦</span><h2>{selected}</h2><p>以下资讯均可追溯至原始链接</p></div><div><strong>{items.length}</strong><span>有效项目线索</span></div><div><strong>{items.filter(x=>x.reliability_level==="high").length}</strong><span>高可信来源</span></div><div><strong>{items.filter(x=>x.cross_source_count>1).length}</strong><span>交叉验证</span></div></div><section className="panel">{items.length ? items.map(x=><ArticleRow key={x.id} article={x} onOpen={onOpen}/>) : <Empty title="暂无匹配资讯" detail="该区域当前没有已入库生产情报。"/>}</section></main></div> : <Empty title="尚无统计数据" detail="采集到海外有效资讯后将自动生成排名。"/>}</>;
}

function Sources({ sources,user,reload,onImport }: {sources:Source[];user:SessionUser;reload:()=>void;onImport:()=>void}) {
  const [type,setType]=useState(""); const [region,setRegion]=useState(""); const [query,setQuery]=useState(""); const [notice,setNotice]=useState(""); const canAdmin=user.role === "admin"; const canImport=ROLE_LEVEL[user.role]>=ROLE_LEVEL.analyst;
  const regions=Array.from(new Set(sources.flatMap(x=>x.region_focus))).filter(Boolean).sort(); const shown=sources.filter(x=>(!type||x.source_type===type)&&(!region||x.region_focus.includes(region))&&(!query||`${x.source_name}${x.country_focus.join()}${x.industry_focus.join()}`.toLowerCase().includes(query.toLowerCase())));
  async function toggle(source:Source) { try { await api(`/api/sources/${source.id}`,{method:"PATCH",body:JSON.stringify({enabled:!source.enabled})}); setNotice("来源状态已更新"); reload(); } catch(e) { setNotice(e instanceof Error?e.message:"更新失败"); } }
  async function run(source:Source) { try { const r=await api<{job_id:string}>(`/api/sources/${source.id}/run`,{method:"POST"}); setNotice(`任务已入队：${r.job_id}`); reload(); } catch(e) { setNotice(e instanceof Error?e.message:"触发失败"); } }
  return <><div className="page-title"><div><div className="eyebrow">SOURCE GOVERNANCE</div><h1>数据源管理</h1><p>只有完成适配并通过合规检查的来源才能自动运行。</p></div>{canImport&&<button className="btn primary" onClick={onImport}>＋ 手动导入</button>}</div>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className="source-metrics"><div><span>来源总数</span><b>{sources.length}</b></div><div><span>可自动运行</span><b>{sources.filter(x=>x.adapter_status==="active"&&x.enabled).length}</b></div><div><span>待适配</span><b>{sources.filter(x=>x.adapter_status==="pending_adapter").length}</b></div><div><span>失败或暂停</span><b>{sources.filter(x=>x.latest_status==="failed"||x.adapter_status==="paused").length}</b></div></div><div className="source-toolbar"><label className="search-field"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索来源、国家或行业"/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="">全部类型</option>{Object.entries(TYPE_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">全部区域</option>{regions.map(x=><option key={x}>{x}</option>)}</select><span>{shown.length} 个来源</span></div><div className="source-table-wrap"><table><thead><tr><th>来源</th><th>类型 / 可信度</th><th>适配状态</th><th>最近运行</th><th>下次计划</th><th>错误 / 新增</th><th>启用</th><th>操作</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><b>{x.source_name}</b><a href={x.source_url} target="_blank" rel="noreferrer">打开原站 →</a></td><td><span>{TYPE_LABEL[x.source_type]||x.source_type}</span><Level level={x.reliability_level}/></td><td><span className={`status ${x.adapter_status}`}>{STATUS_LABEL[x.adapter_status]||x.adapter_status}</span><small>{x.crawl_method}</small></td><td><span>{x.latest_status === "never" ? "从未运行" : x.latest_status}</span><small>{fmt(x.last_success_at||x.last_failure_at)}</small></td><td>{fmt(x.next_run_at)}</td><td><span>{x.latest_failure_reason||`新增 ${x.latest_new_count} 条`}</span><small>{x.consecutive_failures ? `连续失败 ${x.consecutive_failures} 次` : ""}</small></td><td><button disabled={!canAdmin||!["active","manual_only","paused"].includes(x.adapter_status)} className={`switch ${x.enabled?"on":""}`} onClick={()=>toggle(x)}><i/></button></td><td><button className="run-btn" disabled={!canAdmin||!x.enabled||x.adapter_status!=="active"} onClick={()=>run(x)}>立即抓取</button></td></tr>)}</tbody></table></div></>;
}

function Detail({ article,user,onClose,onChange }: {article:Article;user:SessionUser;onClose:()=>void;onChange:()=>void}) {
  async function favorite() { await api(`/api/articles/${article.id}/favorite`,{method:article.favorite?"DELETE":"PUT"}); onChange(); }
  return <div className="overlay"><aside className="drawer">
    <div className="drawer-head"><div><div className="eyebrow">TRACEABLE INTELLIGENCE</div><h2>{article.title}</h2></div><button className="icon-btn" onClick={onClose}>×</button></div>
    <div className="drawer-badges"><Level level={article.reliability_level}/><span className="badge category">{TYPE_LABEL[article.source_type]}</span><span className="badge verified">{article.is_primary_source?"一手来源":"非一手来源"}</span>{ROLE_LEVEL[user.role]>=2&&<button className="btn ghost" onClick={favorite}>{article.favorite?"取消收藏":"收藏"}</button>}</div>
    {article.verification_notice&&<div className="verification-alert"><b>核验提示</b><span>{article.verification_notice}</span></div>}
    <section><h4>资讯摘要</h4><p className="lead">{article.summary||"暂无摘要"}</p></section>
    <section className="insight-box"><h4>销售洞察 <small>来源等级：{reliabilityText(article.reliability_level)}</small></h4><p>{article.sales_insight||"尚未生成销售洞察。"}</p>{(article.ai_payload?.next_action||article.ai_payload?.recommended_sales_action)&&<div className="action-line"><b>建议行动</b><span>{article.ai_payload.next_action||article.ai_payload.recommended_sales_action}</span></div>}</section>
    <section><h4>识别与验证</h4><div className="detail-grid"><div><label>国家 / 区域</label><p>{article.country||"待识别"} / {article.region||"待识别"}</p></div><div><label>命中 KA</label><p>{article.ka.join("、")||"无"}</p></div><div><label>KA 识别依据</label><p>{article.ka_match_evidence.join("；")||"无"}</p></div><div><label>海外识别依据</label><p>{article.overseas_evidence.join("；")||"无"}</p></div><div><label>多源交叉验证</label><p>{article.cross_source_count>1?`是（${article.cross_source_count} 个来源）`:"否"}</p></div><div><label>审核状态</label><p>{article.review_status}</p></div></div></section>
    <section><h4>来源与追溯</h4><div className="source-card"><div><b>{article.source_name}</b><span>{TYPE_LABEL[article.source_type]} · {reliabilityText(article.reliability_level)}</span></div><dl><dt>发布时间</dt><dd>{fmt(article.published_at)}</dd><dt>抓取时间</dt><dd>{fmt(article.fetched_at)}</dd><dt>原始链接</dt><dd><a href={article.original_url} target="_blank" rel="noreferrer">打开原始网页 →</a></dd></dl></div>
      {(article.supporting_sources||[]).filter(x=>!x.is_primary).map(x=><div className="supporting-source" key={x.original_url}><div><b>补充来源 · {reliabilityText(x.reliability_level)}</b><span>{x.title}</span></div><a href={x.original_url} target="_blank" rel="noreferrer">查看原文 →</a></div>)}
    </section>
  </aside></div>;
}

function ImportModal({sources,onClose,onDone}:{sources:Source[];onClose:()=>void;onDone:()=>void}) {
  const manual=sources.filter(x=>x.adapter_status==="manual_only"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [kind,setKind]=useState("wechat");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));const localPublishedAt=String(data.published_at||"");try{await api("/api/articles/manual-import",{method:"POST",body:JSON.stringify({...data,published_at:localPublishedAt?new Date(localPublishedAt).toISOString():null})});onDone()}catch(ex){setError(ex instanceof Error?ex.message:"导入失败")}finally{setBusy(false)}}
  return <div className="overlay"><form className="modal" onSubmit={submit}><div className="modal-head"><div><div className="eyebrow">MANUAL IMPORT</div><h2>手动导入公众号 / 网页文章</h2><p>公众号不会自动抓取；入库后固定作为线索处理。</p></div><button type="button" className="icon-btn" onClick={onClose}>×</button></div>{error&&<div className="login-error">{error}</div>}<div className="form-grid"><label className="wide">原始链接<input name="original_url" type="url" required/></label><label>标题<input name="title" required/></label><label>来源名称{kind==="wechat"?<select name="source_name" required>{manual.filter(x=>x.source_type==="wechat_manual").map(x=><option key={x.id}>{x.source_name}</option>)}</select>:<input name="source_name" required placeholder="网页或机构名称"/>}</label><label>发布时间<input name="published_at" type="datetime-local"/></label><label>导入类型<select name="import_type" value={kind} onChange={e=>setKind(e.target.value)}><option value="wechat">微信公众号</option><option value="web">普通网页</option></select></label><label className="wide">正文<textarea name="content_text" minLength={20} rows={9} required/></label></div><div className="compliance"><b>合规提示</b> 关键金额、中标、合同和业主信息必须核验官方来源。</div><div className="modal-actions"><button type="button" className="btn ghost" onClick={onClose}>取消</button><button className="btn primary" disabled={busy}>{busy?"导入中…":"导入线索"}</button></div></form></div>;
}

export default function Home() {
  const [user,setUser]=useState<SessionUser|null>(null); const [authLoading,setAuthLoading]=useState(true); const [view,setView]=useState("dashboard"); const [filter,setFilter]=useState(""); const [articles,setArticles]=useState<Article[]>([]); const [sources,setSources]=useState<Source[]>([]); const [status,setStatus]=useState<Status|null>(null); const [stats,setStats]=useState<Stats|null>(null); const [loading,setLoading]=useState(false); const [detail,setDetail]=useState<Article|null>(null); const [importing,setImporting]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async(q="",level="")=>{if(!user)return;setLoading(true);setError("");try{const params=new URLSearchParams({limit:"100"});if(q)params.set("q",q);if(level)params.set("reliability",level);const [feed,sourceList,health,statistics]=await Promise.all([api<{items:Article[]}>(`/api/articles?${params}`),api<Source[]>("/api/sources"),api<Status>("/api/dashboard/status"),api<Stats>("/api/stats")]);setArticles(feed.items);setSources(sourceList);setStatus(health);setStats(statistics)}catch(e){setError(e instanceof Error?e.message:"数据加载失败")}finally{setLoading(false)}},[user]);
  useEffect(()=>{(async()=>{if(!hasSession()){setAuthLoading(false);return}try{setUser(await api<SessionUser>("/api/auth/me"))}catch{clearSession()}finally{setAuthLoading(false)}})()},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const navigate=(next:string,f="")=>{setView(next);setFilter(f);window.scrollTo({top:0,behavior:"smooth"})}; const open=async(a:Article)=>{try{setDetail(await api<Article>(`/api/articles/${a.id}`))}catch{setDetail(a)}if(!a.read&&ROLE_LEVEL[user!.role]>=2){try{await api(`/api/articles/${a.id}/read`,{method:"PUT"});setArticles(xs=>xs.map(x=>x.id===a.id?{...x,read:true}:x))}catch{}}};
  const content=(()=>{if(view==="dashboard")return <Dashboard articles={articles} status={status} stats={stats} navigate={navigate} onOpen={open}/>;if(view==="intelligence")return <Feed articles={articles} loading={loading} onOpen={open} onSearch={load}/>;if(view==="country"||view==="region")return <Opportunity key={`${view}:${filter}`} kind={view} data={(view==="country"?stats?.countries:stats?.regions)||[]} articles={articles} initial={filter} onOpen={open}/>;return <Sources sources={sources} user={user!} reload={()=>load()} onImport={()=>setImporting(true)}/>})();
  if(authLoading)return <main className="boot-screen">正在连接安全工作台…</main>; if(!user)return <Login onSuccess={setUser}/>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">SE</span><div><b>海外销售情报</b><small>Schneider Electric</small></div></div><nav>{NAV.map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>navigate(id)}><span>•</span>{label}{id==="sources"&&<i>{sources.length}</i>}</button>)}</nav><div className="sidebar-foot"><div className="coverage"><span>生产数据</span><b>{articles.length} 条有效情报</b><i><em style={{width:status?.delay_status==="healthy"?"100%":"35%"}}/></i><small>{status?.last_successful_update?`更新于 ${fmt(status.last_successful_update)}`:"等待首次成功抓取"}</small></div><button className="user" onClick={async()=>{await logout();setUser(null)}}><span>{user.full_name.slice(0,2)}</span><div><b>{user.full_name}</b><small>{user.role} · 退出登录</small></div></button></div></aside><div className="workspace"><header className="topbar"><div><b>销售情报工作台</b><small className="api-indicator"><i className={error?"bad":""}/>{error?error:"API 已连接"}</small></div><div className="top-actions"><button className="sync" onClick={()=>load()} disabled={loading}>{loading?"更新中…":status?.is_updating?"抓取运行中":"刷新数据"}</button></div></header><main>{content}</main></div>{detail&&<Detail article={detail} user={user} onClose={()=>setDetail(null)} onChange={async()=>{await load();setDetail(null)}}/>}{importing&&<ImportModal sources={sources} onClose={()=>setImporting(false)} onDone={()=>{setImporting(false);load()}}/>}</div>;
}
